### ISSUE TITLE
lack of customizations to make the homepage similar to one shown in demo

### ISSUE THREAD

**Issue by UnnitMetaliya** [thepinecode/wp-theme-alpha#9]
Hi,

Great theme and great work. Thanks for making it open source. I appreciate it.

I was really impressed with demo which made me use this theme for one of my side project. However, after installing it, homepage of my website is far far away from you have in your demo.

The homepage in demo looks so authentic and can make our sites look like authority.

Would you please share the customization or even style-sheet you used for demo. Or tell the theme users how they can achieve something similar to demo?

**Comment by adamlaki** [comment]
Hey,

Sorry, this theme is still in WIP, so there can be differences between the demo and the current version. We want to submit the final result to the wp.org repository.

Here you can find a basic description: https://pineco.de/projects/theme-alpha/alpha-theme-documentation/

If it is a new WordPress instance, you can visit the Customizer and set up the basic starter settings (with the native solution). If you can't, first, you must install the dependencies to the full potential (CMB2, Kirki Customizer Framework). After the install, you will see the instructions, then set up static pages in the WP admin for the front-page, and blog. Finally, you can go to the Customizer and set up the layouts and colors. You can also set colors to categories (with cover images), for posts and pages on the proper edit screens. There aren't any plus CSS, which made it possible that look.

The starter content is a generic problem with the WordPress themes. The Alpha only will support the native solution so it can be that advanced. We will create proper documentation when it finally arrives at the org repo.

Thanks for your message!
